notebook:
  image:
    repository: ritchie229/ritchie_docker
    tag: notebook-app-web
  replicaCount: 1
  service:
    port: 5000

mysql:
  image:
    repository: mysql
    tag: "8.0"
  rootPassword: rootpass
  database: notebook
  user: user
  password: userpass
  port: 3306
  storage: 1Gi

ingress:
  enabled: true
  className: nginx
  host: notebook.local

